I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rydeas.rpy", line 388, in script call
    $renpy.call(destination)
  File "renpy/common/00start.rpy", line 81, in script
    return
Exception: Could not find return label (u'/Users/Ryan/EbbyDev/Git/Uirusu-Shoujo/game/rydeas_Aids.rpy', 1413515384, 0).

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rydeas.rpy", line 388, in script call
    $renpy.call(destination)
  File "renpy/common/00start.rpy", line 81, in script
    return
  File "/Users/Ryan/EbbyDev/Soft/renpy-6.18.1-sdk/renpy/ast.py", line 1321, in execute
    next_node(renpy.game.context().lookup_return(pop=True))
  File "/Users/Ryan/EbbyDev/Soft/renpy-6.18.1-sdk/renpy/execution.py", line 391, in lookup_return
    raise Exception("Could not find return label {!r}.".format(self.return_stack[-1]))
Exception: Could not find return label (u'/Users/Ryan/EbbyDev/Git/Uirusu-Shoujo/game/rydeas_Aids.rpy', 1413515384, 0).

Darwin-13.3.0-x86_64-i386-64bit
Ren'Py 6.18.1.670
ec 0.0
